### ISSUE TITLE
Jobs indicator shows up even when there are no background jobs

### ISSUE THREAD

**Issue by imgnue** [ajeetdsouza/zoxide#527] opened 2023-01-26 10:09 UTC
I'm using the [starship](https://github.com/starship/starship) prompt and this happens when changing directory. The indicator (✦) disappears when you issue other commands or press enter.

https://user-images.githubusercontent.com/12945959/214809326-d464e6b0-44ba-4ff0-ae8f-fe665d176326.mp4

**Comment by ajeetdsouza** [comment] 2023-01-26 14:11
This looks more like a Starship bug than a zoxide one. zoxide doesn't start any background processes, it just uses the chpwd hook provided by zsh. Please report it on the Starship issue tracker and tag this issue.

**Comment by imgnue** [comment] 2023-01-26 21:50
Will post it there, thanks!

**Comment by ajeetdsouza** [comment] 2023-02-02 08:29
Awesome, closing this issue then.

**Closed by ajeetdsouza** 2023-02-02 08:29 UTC

**Comment by ajeetdsouza** [comment] 2023-06-15 05:13
Tracking this here, too: https://github.com/starship/starship/issues/5159

This is caused by a bug in Bash, but we've found a workaround and it should be fixed soon.
