### ISSUE TITLE
zoxide doesn't match on parent directories

### ISSUE THREAD

**Issue by tekumara** [ajeetdsouza/zoxide#90] opened 2020-06-27 05:37 UTC
zoxide doesn't match on parent directories, eg:
```
$  za /Users/tekumara/Library/Application\ Support/zoxide
$  zq app
Error: no match found
```
Whereas rupa/z will find a match when a parent directory matches:
```
$ z app -l
common:    /Users/tekumara/Library/Application Support/zoxide
239884     /Users/tekumara/Library/Application Support/zoxide
```

**Comment by ajeetdsouza** [comment] 2020-07-01 12:36
Hey @tekumara,

zoxide always ensures that the last keyword in a query matches the actual directory name, so `/home/foo` can be matched with:

- `h foo`
- `home f`
- `home foo`
- `foo`
- `f o o`
- `/foo`
- `home/f`

However, by design, it will not match:

- `home`
- `home/`
- `/home`

IMO, requiring (part of) the name of the directory at the end drastically improves the quality of the results. Usually, if I've forgotten the name of the directory, I just use `zi` to find it.

Is there a reason you would want zoxide to match on parent directories?

**Comment by tekumara** [comment] 2020-07-01 13:21
Even if different from rupa/z that seems fair and workable! It’s probably only really a difference for the first time I’d want to traverse up to a parent. `cd` will suffice 😀 It’s a small adjustment on my part and understanding the logic helps. I might have missed the explanation in the doco.

**Comment by ajeetdsouza** [comment] 2020-07-01 13:41
That's alright, do let me know if you think the README could have been clearer!

Btw, you can use zoxide exactly like cd! The following commands would be completely valid and would not even need to access the database:

- `z ..` (navigate to parent directory)
- `z ../..` (navigate two levels up)
- `z -` (navigate to previous directory)
- `z .` (navigate to current directory, which does nothing)

More examples - all of the following navigate to `/home`:

- `z /home`
- `z /` followed by `z home`
- `z /` followed by `z ./home`

I'm closing this issue, but feel free to re-open it if you have more questions!

**Closed by ajeetdsouza** 2020-07-01 13:41 UTC

**Comment by tekumara** [comment] 2020-07-03 09:30
👍 is there any doco that explains the matching logic?
