### ISSUE TITLE
[nushell] `zoxide init nushell` output contains deprecated list spread

### ISSUE THREAD

**Issue by suttonbradley** [ajeetdsouza/zoxide#681] opened 2024-02-06 23:38 UTC
When I save the output to a file and source it in my nu config, I get the error: "Spreading lists automatically when calling external commands is deprecated and will be removed in 0.91." on line 26 of the file: `def-env __zoxide_z [...rest:string] {`

![image](https://github.com/ajeetdsouza/zoxide/assets/31932528/59479994-7060-4e03-a81c-8d2c799a854e)

**Comment by avi-cenna** [comment] 2024-02-09 22:53
I'm getting this issue too

**Comment by apraga** [comment] 2024-02-10 13:31
Duplicate of #661 : replacing `def-env` with `def --env` should solve the issue.

**Comment by ajeetdsouza** [comment] 2024-02-12 21:45
Fixed.

**Closed by ajeetdsouza** 2024-02-12 21:45 UTC
