### ISSUE TITLE
Set different home directory

### ISSUE THREAD

**Issue by mtwb47** [ajeetdsouza/zoxide#902] opened 2024-10-01 05:07 UTC
I do not use a traditional home directory setup. XDG_HOME exists, but I use another directory as a my default (so my hidden files are truly hidden). When I use the `z` command it takes me to XDG_HOME. Is there a way to set up zoxide to use a different base directory for cd with no arguments? 

For example, I have `cd` set up so that when I run it with no arguments, it takes me to my preferred default directory instead of xdg_home.

I didn't see this as an option in man zoxide, so I thought I'd try asking here.

**Comment by ajeetdsouza** [comment] 2024-10-01 12:04
Duplicate of https://github.com/ajeetdsouza/zoxide/issues/869.

**Closed by ajeetdsouza** 2024-10-01 12:04 UTC

**Comment by mtwb47** [comment] 2024-10-02 19:42
Thanks!
