### ISSUE TITLE
zoxide reports "no match found" when a backslash is appended to the path

### ISSUE THREAD

**Issue by xd003** [ajeetdsouza/zoxide#886] opened 2024-09-13 02:51 UTC
When using `zoxide` to navigate directories, appending a backslash (`\`) to the directory name causes `zoxide` to fail with a "no match found" error, even though the directory exists. Without the backslash, `zoxide` successfully switches to the target directory. This behavior suggests that `zoxide` does not recognize paths with a trailing backslash as valid matches.

![image](https://github.com/user-attachments/assets/8450eb17-4283-41d7-9576-290add7145a5)

zoxide v0.9.4
nushell v0.97.1

**Comment by ajeetdsouza** [comment] 2024-09-13 03:33
Dupe of https://github.com/ajeetdsouza/zoxide/issues/876

**Closed by ajeetdsouza** 2024-09-13 03:33 UTC
