### ISSUE TITLE
zsh autocomplete is not working

### ISSUE THREAD

**Issue by AethanFoot** [ajeetdsouza/zoxide#737] opened 2024-02-27 22:04 UTC
I can't tell if this is an exact repeat or if it is slightly different.

```
zoxide 0.9.4
zsh 5.9 ~Using zinit
Arch Linux
```
I have checked through the init script and it appears to failing in calling the binding on line 92. I tested by manually binding the widget __zoxide_z_complete_helper to the home key, then if I setup when a completion should happen clear it and press my binding, it runs properly. So I am presuming the way printf works has changed in some way such that printing a keycode doesn't activate the key.

**Comment by wytsai7660** [comment] 2024-02-28 10:20
same issue here
```
macOS Sonoma 14.2.1 23C71 arm64
zoxide 0.9.4
zsh 5.9 (x86_64-apple-darwin23.0)
zinit v3.13.1-4-g6511ca7f (darwin23.0_arm64)
```
<img width="922" alt="Screenshot 2024-02-28 at 18 19 48" src="https://github.com/ajeetdsouza/zoxide/assets/116703995/53b8c7c5-650b-42ae-9520-16610b47733b">

**Comment by jakenvac** [comment] 2024-03-08 22:29
I was getting a non zero exit code with the `eval "$(zoxide init zsh)"`. Ended up writing the output to a file and removing the autocomplete setup at the bottom and now I get a zero. 

Something in the init script has broken autocomplete in recent versions.

**Comment by tabedzki** [comment] 2024-05-03 16:10
@AethanFoot can you post your fix that restored the functionality? And is it possible to bind it to the tab key?
Thanks in advance

**Comment by RafaelMoreira1180778** [comment] 2024-07-26 08:24
Same problem, I have:

```zsh
autoload -Uz compinit
compinit
eval "$(zoxide init zsh --cmd cd)"
```

At the end of `.zshrc` but when I click Tab when performing `cd ...` it does not show any direcory.

```zsh
$ zsh --version
zsh 5.9 (x86_64-apple-darwin23.0)

$ zoxide --version
zoxide 0.9.4
```

**Comment by ajeetdsouza** [comment] 2024-09-13 00:08
Duplicate of https://github.com/ajeetdsouza/zoxide/issues/471 - please check my comment in that thread for some basic debugging steps: https://github.com/ajeetdsouza/zoxide/issues/471#issuecomment-2347425881

**Closed by ajeetdsouza** 2024-09-13 00:08 UTC
