### ISSUE TITLE
Support for skim (`sk`)

### ISSUE THREAD

**Issue by victorz** [ajeetdsouza/zoxide#482] opened 2022-11-08 22:26 UTC
Would be super cool if there was support for the _skim_ (`sk`) fuzzy finder, an fzf "clone".

https://github.com/lotabout/skim

**Comment by ajeetdsouza** [comment] 2022-11-09 08:04
Duplicate of https://github.com/ajeetdsouza/zoxide/issues/228. There are a couple of reasons to not officially support skim, please see my comment there.

**Closed by ajeetdsouza** 2022-11-09 08:04 UTC
