### ISSUE TITLE
tab completion without <SPACE>

### ISSUE THREAD

**Issue by kujohn** [ajeetdsouza/zoxide#747] opened 2024-03-07 20:14 UTC
Is there anyway to remap the interactive completion with just `<TAB>` and not `<SPACE><TAB>`?

**Comment by ajeetdsouza** [comment] 2024-05-05 15:01
Duplicate of https://github.com/ajeetdsouza/zoxide/issues/484.

**Closed by ajeetdsouza** 2024-05-05 15:01 UTC
