### ISSUE TITLE
dir with `/` at the end is not found globally

### ISSUE THREAD

**Issue by dev-ardi** [ajeetdsouza/zoxide#909] opened 2024-10-07 10:45 UTC
Intended workflow:

1. `mkdir my_dir`
2. `z my` - shell autocompletes this to my_dir/`
3. on another terminal, using a global history tool like atuin use the last command

A way to fix this would be - if a local `my_dir` is not found then go to do the normal search without the `/`

**Comment by WiIIiamWei** [comment] 2024-10-07 12:58
Dupe of #876.

**Closed** 2024-10-07 13:56 UTC
