### ISSUE TITLE
Only show results under current directory when dot is first argument

### ISSUE THREAD

**Issue by SeerLite** [ajeetdsouza/zoxide#907] opened 2024-10-06 01:38 UTC
For example if I'm in `~/repos/project` and there's a directory `~/repos/project/here/be/tests`.
Doing `z test` would take me to my most frequently visited directory `~/frequently_visited_tests`.
Doing `z . test` would take me to the most frequently visited directory _under this directory_ `~/repos/project/here/be/tests`.

**Comment by ajeetdsouza** [comment] 2024-10-06 08:49
Duplicate of https://github.com/ajeetdsouza/zoxide/issues/800

**Closed by ajeetdsouza** 2024-10-06 08:49 UTC

**Comment by SeerLite** [comment] 2024-10-10 02:17
Thank you and sorry!
