### ISSUE TITLE
Interactive completions using z term<space><tab> don't work in fish, zi works

### ISSUE THREAD

**Issue by rickythefox** [ajeetdsouza/zoxide#372] opened 2022-03-31 22:38 UTC
Entering `z term<space><tab>` brings up fzf but the selection made is not used to do the jump, I just get a bell. 

`zi` works fine - brings up fzf and performs the jump.
In zsh `z term<space><tab>` works as expected.

**Comment by ajeetdsouza** [comment] 2022-04-01 00:15
Duplicate of https://github.com/ajeetdsouza/zoxide/issues/341

**Closed by ajeetdsouza** 2022-04-01 00:15 UTC
