### ISSUE TITLE
skim over fzf

### ISSUE THREAD

**Issue by alexxbb** [ajeetdsouza/zoxide#31] opened 2020-03-12 23:04 UTC
Thank you, works great!

I'd much prefer to use [skim](https://github.com/lotabout/skim) over fzf

**Comment by ajeetdsouza** [comment] 2020-03-12 23:09
Duplicate of https://github.com/ajeetdsouza/zoxide/issues/3

We decided not to go with `skim` for now, because it does not support Windows, and we're moving towards being cross-platform.

**Closed by ajeetdsouza** 2020-03-12 23:09 UTC
