### ISSUE TITLE
could not create database c:\path\to\zoxide\db.zo: access is denied

### ISSUE THREAD

**Issue by fdncred** [ajeetdsouza/zoxide#103] opened 2020-08-26 18:52 UTC
nushell is failing tests with the error in the title. any ideas what's going on?  i assume that it's running tests in parallel and trying to exclusively lock the db.zo file and getting denied, but i'm not sure.

**Comment by ajeetdsouza** [comment] 2020-08-27 06:56
Hmm, it does look like an issue with concurrent writes. I've only ever tested concurrency on Linux - I ran `zoxide add /tmp` on my Linux system in an infinite loop on 20 separate terminals, and it ran for quite a while with no hiccups:

![zoxide](https://user-images.githubusercontent.com/1777663/91406361-dcabb880-e85f-11ea-8d0c-3340bca2073f.png)

The problem seems to be that zoxide's write operation uses `rename()`, which is guaranteed to be atomic on POSIX compliant operating systems, but not on Windows. I don't currently have a Windows system available to test, but I'll see what I can do about this.

**Comment by fdncred** [comment] 2020-08-27 13:18
I have windows boxes. Let me know how/if I can help test something for you.

**Comment by ajeetdsouza** [comment] 2020-08-27 20:48
@fdncred would you be able to build the `atomic` branch and see if it still fails the Nushell tests?

**Comment by fdncred** [comment] 2020-08-28 13:37
Just ran it with
```
❯ zoxide --version
zoxide v0.4.3-6-g440b8b2
```
and it produced the same results in `nu`. `test result: FAILED. 5 passed; 31 failed; 0 ignored; 0 measured; 0 filtered out`

<details>
<summary>Nushell Test Details</summary>

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running C:\cargo_target_dir\debug\deps\nu_plugin_core_fetch-c1acf72fcc203cbf.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running C:\cargo_target_dir\debug\deps\nu_plugin_core_inc-598624215d4e45a7.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running C:\cargo_target_dir\debug\deps\nu_plugin_core_match-1870675c253f7ee4.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running C:\cargo_target_dir\debug\deps\nu_plugin_core_post-a0f7ca1f191d68ef.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running C:\cargo_target_dir\debug\deps\nu_plugin_core_ps-f9e0e5eaa5f214e2.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running C:\cargo_target_dir\debug\deps\nu_plugin_core_sys-ad95fc0a79d7c026.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running C:\cargo_target_dir\debug\deps\nu_plugin_core_textview-670589c5249ef74b.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running C:\cargo_target_dir\debug\deps\main-70a471caf36378de.exe

running 36 tests
test shell::pipeline::commands::external::correctly_escape_external_arguments ... FAILED
test shell::pipeline::commands::external::it_evaluation::supports_fetching_given_a_column_path_to_it ... FAILED
test shell::pipeline::commands::external::external_command_arguments::expands_table_of_primitives_to_positional_arguments ... FAILED
test shell::pipeline::commands::external::it_evaluation::takes_rows_of_nu_value_lines ... FAILED
test shell::pipeline::commands::external::it_evaluation::takes_rows_of_nu_value_strings ... FAILED
test shell::pipeline::commands::external::stdin_evaluation::does_not_block_indefinitely ... FAILED
test shell::pipeline::commands::external::external_words::no_escaping_for_single_quoted_strings ... FAILED
test shell::pipeline::commands::external::automatically_change_directory_with_trailing_slash_and_same_name_as_command ... FAILED
test shell::pipeline::commands::external::external_words::relaxed_external_words ... FAILED
test shell::pipeline::commands::external::nu_commands::echo_internally_externally ... FAILED
test shell::pipeline::commands::external::nu_script::run_nu_script ... FAILED
test shell::pipeline::commands::external::nu_script::run_nu_script_multiline ... FAILED
test shell::pipeline::commands::external::stdin_evaluation::does_not_panic_with_no_newline_in_stream ... ok
test shell::pipeline::commands::internal::can_process_one_row_from_internal_and_pipes_it_to_stdin_of_external ... FAILED
test shell::pipeline::commands::external::tilde_expansion::as_home_directory_when_passed_as_argument_and_begins_with_tilde ... ok
test shell::pipeline::commands::external::tilde_expansion::does_not_expand_when_passed_as_argument_and_does_not_start_with_tilde ... FAILED
test shell::pipeline::commands::internal::argument_invocation ... FAILED
test shell::pipeline::commands::internal::autoenv ... FAILED
test shell::pipeline::commands::internal::echoing_ranges ... FAILED
test shell::pipeline::commands::internal::invocation_handles_dot ... FAILED
test shell::pipeline::commands::internal::parse::errors_if_flag_is_not_supported ... ok
test shell::pipeline::commands::internal::invocation_properly_redirects ... FAILED
test shell::pipeline::commands::internal::it_expansion_of_list ... FAILED
test shell::pipeline::commands::internal::it_expansion_of_invocation ... FAILED
test shell::pipeline::commands::internal::parse::errors_if_passed_an_unexpected_argument ... ok
test shell::pipeline::commands::internal::proper_it_expansion ... FAILED
test shell::pipeline::commands::internal::string_interpolation_with_column ... FAILED
test shell::pipeline::commands::internal::string_interpolation_with_column3 ... FAILED
test shell::pipeline::commands::internal::string_interpolation_with_column2 ... FAILED
test shell::pipeline::commands::internal::string_interpolation_with_it_column_path ... FAILED
test shell::pipeline::commands::internal::string_interpolation_with_it ... FAILED
test shell::pipeline::commands::internal::takes_rows_of_nu_value_strings_and_pipes_it_to_stdin_of_external ... FAILED
test shell::pipeline::doesnt_break_on_utf8 ... FAILED
test shell::pipeline::commands::internal::tilde_expansion::as_home_directory_when_passed_as_argument_and_begins_with_tilde ... FAILED
test shell::pipeline::commands::internal::parse::errors_if_flag_passed_is_not_exact ... ok
test shell::pipeline::commands::internal::tilde_expansion::does_not_expand_when_passed_as_argument_and_does_not_start_with_tilde ... FAILED

failures:

---- shell::pipeline::commands::external::correctly_escape_external_arguments stdout ----
=== stderr

thread 'shell::pipeline::commands::external::correctly_escape_external_arguments' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"$0"`', tests\shell\pipeline\commands\external.rs:68:5

---- shell::pipeline::commands::external::it_evaluation::supports_fetching_given_a_column_path_to_it stdout ----
=== stderr

thread 'shell::pipeline::commands::external::it_evaluation::supports_fetching_given_a_column_path_to_it' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"zion"`', tests\shell\pipeline\commands\external.rs:147:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- shell::pipeline::commands::external::external_command_arguments::expands_table_of_primitives_to_positional_arguments stdout ----
=== stderr

thread 'shell::pipeline::commands::external::external_command_arguments::expands_table_of_primitives_to_positional_arguments' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"andres_likes_arepas.txt ferris_not_here.txt jonathan_likes_cake.txt"`', tests\shell\pipeline\commands\external.rs:297:17

---- shell::pipeline::commands::external::it_evaluation::takes_rows_of_nu_value_lines stdout ----
=== stderr

thread 'shell::pipeline::commands::external::it_evaluation::takes_rows_of_nu_value_lines' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"AndrásWithKitKat"`', tests\shell\pipeline\commands\external.rs:124:13

---- shell::pipeline::commands::external::it_evaluation::takes_rows_of_nu_value_strings stdout ----
=== stderr

thread 'shell::pipeline::commands::external::it_evaluation::takes_rows_of_nu_value_strings' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"jonathan_likes_cake.txt"`', tests\shell\pipeline\commands\external.rs:97:13

---- shell::pipeline::commands::external::stdin_evaluation::does_not_block_indefinitely stdout ----
=== stderr

thread 'shell::pipeline::commands::external::stdin_evaluation::does_not_block_indefinitely' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"y"`', tests\shell\pipeline\commands\external.rs:183:9

---- shell::pipeline::commands::external::external_words::no_escaping_for_single_quoted_strings stdout ----
=== stderr

thread 'shell::pipeline::commands::external::external_words::no_escaping_for_single_quoted_strings' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"test \"things\""`', tests\shell\pipeline\commands\external.rs:205:9

---- shell::pipeline::commands::external::automatically_change_directory_with_trailing_slash_and_same_name_as_command stdout ----
=== stderr

thread 'shell::pipeline::commands::external::automatically_change_directory_with_trailing_slash_and_same_name_as_command' panicked at 'assertion failed: actual.out.ends_with("cd")', tests\shell\pipeline\commands\external.rs:60:9

---- shell::pipeline::commands::external::external_words::relaxed_external_words stdout ----
=== stderr

thread 'shell::pipeline::commands::external::external_words::relaxed_external_words' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"joturner@foo.bar.baz"`', tests\shell\pipeline\commands\external.rs:196:9

---- shell::pipeline::commands::external::nu_commands::echo_internally_externally stdout ----
=== stderr

thread 'shell::pipeline::commands::external::nu_commands::echo_internally_externally' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"foo"`', tests\shell\pipeline\commands\external.rs:218:9

---- shell::pipeline::commands::external::nu_script::run_nu_script stdout ----
=== stderr

thread 'shell::pipeline::commands::external::nu_script::run_nu_script' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"done"`', tests\shell\pipeline\commands\external.rs:231:9

---- shell::pipeline::commands::external::nu_script::run_nu_script_multiline stdout ----
=== stderr

thread 'shell::pipeline::commands::external::nu_script::run_nu_script_multiline' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"23"`', tests\shell\pipeline\commands\external.rs:240:9

---- shell::pipeline::commands::internal::can_process_one_row_from_internal_and_pipes_it_to_stdin_of_external stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::can_process_one_row_from_internal_and_pipes_it_to_stdin_of_external' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"nushell"`', tests\shell\pipeline\commands\internal.rs:406:5

---- shell::pipeline::commands::external::tilde_expansion::does_not_expand_when_passed_as_argument_and_does_not_start_with_tilde stdout ----
=== stderr

thread 'shell::pipeline::commands::external::tilde_expansion::does_not_expand_when_passed_as_argument_and_does_not_start_with_tilde' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"1~1"`', tests\shell\pipeline\commands\external.rs:271:9

---- shell::pipeline::commands::internal::argument_invocation stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::argument_invocation' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"foo"`', tests\shell\pipeline\commands\internal.rs:296:5

---- shell::pipeline::commands::internal::autoenv stdout ----
=== stderr
error: Error: "D:\\Temp\\.tmpTlM5Fv\\autoenv_test\\.nu-env" is untrusted. Run 'autoenv trust "D:\\Temp\\.tmpTlM5Fv\\autoenv_test"' to trust it.
This needs to be done after each change to the file.


thread 'shell::pipeline::commands::internal::autoenv' panicked at 'assertion failed: actual.out.ends_with("testvalue")', tests\shell\pipeline\commands\internal.rs:96:9

---- shell::pipeline::commands::internal::echoing_ranges stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::echoing_ranges' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"6"`', tests\shell\pipeline\commands\internal.rs:418:5

---- shell::pipeline::commands::internal::invocation_handles_dot stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::invocation_handles_dot' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"AndKitKat"`', tests\shell\pipeline\commands\internal.rs:324:9

---- shell::pipeline::commands::internal::invocation_properly_redirects stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::invocation_properly_redirects' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"hello"`', tests\shell\pipeline\commands\internal.rs:284:5

---- shell::pipeline::commands::internal::it_expansion_of_list stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::it_expansion_of_list' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"[\"bar\",\"foo\"]"`', tests\shell\pipeline\commands\internal.rs:260:5

---- shell::pipeline::commands::internal::it_expansion_of_invocation stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::it_expansion_of_invocation' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"4"`', tests\shell\pipeline\commands\internal.rs:272:5

---- shell::pipeline::commands::internal::proper_it_expansion stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::proper_it_expansion' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"[\"andres.txt\",\"gedge.txt\",\"jonathan.txt\",\"yehuda.txt\"]"`', tests\shell\pipeline\commands\internal.rs:244:9

---- shell::pipeline::commands::internal::string_interpolation_with_column stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::string_interpolation_with_column' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"bob is cool"`', tests\shell\pipeline\commands\internal.rs:349:5

---- shell::pipeline::commands::internal::string_interpolation_with_column3 stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::string_interpolation_with_column3' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"also sally"`', tests\shell\pipeline\commands\internal.rs:373:5

---- shell::pipeline::commands::internal::string_interpolation_with_column2 stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::string_interpolation_with_column2' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"also fred is cool"`', tests\shell\pipeline\commands\internal.rs:361:5

---- shell::pipeline::commands::internal::string_interpolation_with_it_column_path stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::string_interpolation_with_it_column_path' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"sammie"`', tests\shell\pipeline\commands\internal.rs:385:5

---- shell::pipeline::commands::internal::string_interpolation_with_it stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::string_interpolation_with_it' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"foo"`', tests\shell\pipeline\commands\internal.rs:337:5

---- shell::pipeline::commands::internal::takes_rows_of_nu_value_strings_and_pipes_it_to_stdin_of_external stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::takes_rows_of_nu_value_strings_and_pipes_it_to_stdin_of_external' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"Ecuado"`', tests\shell\pipeline\commands\internal.rs:37:9

---- shell::pipeline::doesnt_break_on_utf8 stdout ----
=== stderr

thread 'shell::pipeline::doesnt_break_on_utf8' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"ö"`: '' should contain ö', tests\shell\pipeline\mod.rs:9:5

---- shell::pipeline::commands::internal::tilde_expansion::as_home_directory_when_passed_as_argument_and_begins_with_tilde stdout ----
=== stderr

note: test did not panic as expected
---- shell::pipeline::commands::internal::tilde_expansion::does_not_expand_when_passed_as_argument_and_does_not_start_with_tilde stdout ----
=== stderr

thread 'shell::pipeline::commands::internal::tilde_expansion::does_not_expand_when_passed_as_argument_and_does_not_start_with_tilde' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"1~1"`', tests\shell\pipeline\commands\internal.rs:513:9


failures:
    shell::pipeline::commands::external::automatically_change_directory_with_trailing_slash_and_same_name_as_command
    shell::pipeline::commands::external::correctly_escape_external_arguments
    shell::pipeline::commands::external::external_command_arguments::expands_table_of_primitives_to_positional_arguments
    shell::pipeline::commands::external::external_words::no_escaping_for_single_quoted_strings
    shell::pipeline::commands::external::external_words::relaxed_external_words
    shell::pipeline::commands::external::it_evaluation::supports_fetching_given_a_column_path_to_it
    shell::pipeline::commands::external::it_evaluation::takes_rows_of_nu_value_lines
    shell::pipeline::commands::external::it_evaluation::takes_rows_of_nu_value_strings
    shell::pipeline::commands::external::nu_commands::echo_internally_externally
    shell::pipeline::commands::external::nu_script::run_nu_script
    shell::pipeline::commands::external::nu_script::run_nu_script_multiline
    shell::pipeline::commands::external::stdin_evaluation::does_not_block_indefinitely
    shell::pipeline::commands::external::tilde_expansion::does_not_expand_when_passed_as_argument_and_does_not_start_with_tilde
    shell::pipeline::commands::internal::argument_invocation
    shell::pipeline::commands::internal::autoenv
    shell::pipeline::commands::internal::can_process_one_row_from_internal_and_pipes_it_to_stdin_of_external
    shell::pipeline::commands::internal::echoing_ranges
    shell::pipeline::commands::internal::invocation_handles_dot
    shell::pipeline::commands::internal::invocation_properly_redirects
    shell::pipeline::commands::internal::it_expansion_of_invocation
    shell::pipeline::commands::internal::it_expansion_of_list
    shell::pipeline::commands::internal::proper_it_expansion
    shell::pipeline::commands::internal::string_interpolation_with_column
    shell::pipeline::commands::internal::string_interpolation_with_column2
    shell::pipeline::commands::internal::string_interpolation_with_column3
    shell::pipeline::commands::internal::string_interpolation_with_it
    shell::pipeline::commands::internal::string_interpolation_with_it_column_path
    shell::pipeline::commands::internal::takes_rows_of_nu_value_strings_and_pipes_it_to_stdin_of_external
    shell::pipeline::commands::internal::tilde_expansion::as_home_directory_when_passed_as_argument_and_begins_with_tilde
    shell::pipeline::commands::internal::tilde_expansion::does_not_expand_when_passed_as_argument_and_does_not_start_with_tilde
    shell::pipeline::doesnt_break_on_utf8

test result: FAILED. 5 passed; 31 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p nu --test main'

</details>

**Comment by ajeetdsouza** [comment] 2020-09-11 21:41
I'm not sure there's a perfect solution to atomic file writes on Windows.

- In C++, [`std::filesystem::rename`](https://en.cppreference.com/w/cpp/filesystem/rename) is expected to behave like a POSIX `rename` (which is atomic). The [MSVC implementation](https://github.com/microsoft/STL/blob/9e76d8c3d3700e086f3fbedd0c5b71f1678e4796/stl/src/filesystem.cpp#L751) uses `MoveFileExW`, which is not guaranteed to be atomic. The [Rust implementation](https://github.com/rust-lang/rust/blob/ac48e62db85e6db4bbe026490381ab205f4a614d/library/std/src/sys/windows/fs.rs#L712) also uses `MoveFileExW`.
- This [CppCon talk](https://www.youtube.com/watch?v=uhRWMGBjlO8) suggests using `SetFileInformationByHandle` with `FILE_RENAME_INFO` and `ReplaceIfExists = true`. Nowhere in the [docs](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileinformationbyhandle) is anything mentioned about the operation being atomic.
- The [rust-atomicwrites](https://github.com/untitaker/rust-atomicwrites) [implementation](https://github.com/untitaker/rust-atomicwrites/blob/7ed5d95896812c1ff8522cc3ffa220e267137d30/src/lib.rs#L215) also uses `MoveFileExW`.
- There appears to be a new flag (`FILE_RENAME_FLAG_POSIX_SEMANTICS`) introduced in Windows 10 1607 that appears promising. However, using this will break zoxide for users of older versions of Windows.

**Comment by fdncred** [comment] 2020-09-12 09:01
Wow, you've done a lot of research. I suspect some of your research [came from here](https://stackoverflow.com/questions/167414/is-an-atomic-file-rename-with-overwrite-possible-on-windows) which seems to be a good source with several options.

If there's a way [to use this](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-replacefilew), it may be closer to what you really want to do.

It also may be worth a try to use `SetFileInformationByHandle` and see what happens. Let me know if you want me to test something again.

**Comment by ajeetdsouza** [comment] 2020-09-19 21:23
> If there's a way to use `ReplaceFileW`, it may be closer to what you really want to do.

Strangely enough, `ReplaceFileW`, although [recommended by Microsoft](https://docs.microsoft.com/en-us/windows/win32/fileio/deprecation-of-txf) for exactly this use case, has a glaring problem - it only works when the destination exists. Since there is no way to atomically check that the destination exists and then call `ReplaceFileW`, we can't really use this.

> It also may be worth a try to use `SetFileInformationByHandle`.

I'm not so sure about this, since it breaks zoxide on older Windows versions. Besides

---

Nearly every language is struggling with this exact problem, and they've all eventually settled with `MoveFileExW` with the `MOVEFILE_REPLACE_EXISTING` flag enabled. In addition to C++ and Rust, which I mentioned in the last comment:

- [Python](https://bugs.python.org/issue8828): introduced `os.replace` in an attempt to get atomic renames. The [source](https://github.com/python/cpython/blob/0c71a66b53f6ea262aa5a60784c8c625ae0bb98c/Modules/posixmodule.c#L4379) shows that they use `MoveFileExW` for this.
- [OCaml](https://github.com/ocaml/ocaml/pull/1306): the PR does note that `MoveFileExW` is not always atomic, but they have settled with "best effort", since an actual guaranteed atomic rename is impossible on Windows.
- [Go](https://github.com/golang/go/issues/8914): closed the issue asking for atomic writes on Windows, since it was impossible to do.

---

I borrowed a Windows laptop to test. I was able to reproduce the problem by running `while($true){zoxide add}` on 3 terminals.

I did find a way to make it work. I don't particularly like the solution, because it's hacky and zoxide doesn't really need to be this highly parallelizable, but here it is:

- Try to replace the existing database using `std::fs::rename` aka `MoveFileEx`.
- If it fails with `PermissionDenied`, sleep for 100ms and try again.
- If it fails more than 10 times, throw the error.

The sleep ensures that the other zoxide instances have time to complete their writes, and also restricts the maximum possible delay to 1 second. I did see someone rant on one thread about how I/O in Windows is basically "try, try, till you succeed", so it appears I'm not alone here.

**Comment by fdncred** [comment] 2020-09-21 19:55
Seems like a reasonable approach. Can't wait to try it out.

**Comment by ajeetdsouza** [comment] 2020-10-20 06:22
@fdncred whoops, completely forgot about this. I've added this in https://github.com/ajeetdsouza/zoxide/commit/3d432105e045ceb879f0dd0e66fb72db994a2e3b, could you retry the test?

**Comment by fdncred** [comment] 2020-10-20 12:52
To be fair, there are known problems with how nushell runs tests. For instance, if I have a config.toml with a lot of settings, those settings, regardless of zoxide, will cause tests to fail.

However, you'll notice that there still are access issues. There are a bunch of these while running tests, this is just a snippet.


![image](https://user-images.githubusercontent.com/343840/96588078-c7c03400-12a8-11eb-947a-3f199e38e47b.png)

**Comment by ajeetdsouza** [comment] 2020-10-26 19:30
@fdncred could you share exactly how you're setting up zoxide on nushell and running the tests? I ran `while($true){zoxide add}` on 10 separate terminals on Windows, but I'm unable to reproduce the issue with the latest change.

Also, I randomized the wait period between retries, which should further reduce the likelihood of the error.

**Comment by fdncred** [comment] 2020-10-26 21:16
I run tests with this powershell script.
```powershell
function run_tests {
    $env:RUSTFLAGS="-D warnings"
    cargo test --all
}
```
i have these aliases, among others, in my nushell config.toml
```
    "alias zi [a b c d] {echo $(do -i {zoxide query -i $a $b $c $d} | str trim) | cd $it}",
    "alias za [a b c d] {zoxide add $a $b $c $d}",
    "alias zq [a b c d] {zoxide query -- $a $b $c $d}",
    "alias zl [] {zoxide query --list}",
    "alias zqi [a b c d] {echo $(do -i {zoxide query -i $a $b $c $d}) | cd $it}",
    "alias zr [a b c d] {zoxide remove $a $b $c $d}",
    "alias zri [a b c d] {zoxide remove -i $a $b $c $d}",
    "alias z [a b c d] {if $(echo $a | empty?) == $true { cd ~ } {echo $a | if $it == '-' { cd - } {cd $(zoxide query -- $a $b $c $d | str trim)}}}",
    "alias set_title_str [str-arg] {echo [$(char title) ' ' $str-arg ' ' $(char bel)] | str collect}",
    "alias get_abbrev_pwd_win [] {echo [$(pwd | split row '\\' | first $(pwd | split row '\\' | count | each {= $it - 1} ) |  str substring '0,1' | format '{$it}/' | append $(pwd | split row '\\' | last ) | str collect)] | str collect}",
    "alias set_title [] {set_title_str $(echo $(get_abbrev_pwd_win))}",
    "alias git_br [] {echo [ $(ansi gb) $(pwd) $(ansi reset) '(' $(ansi cb) $(do -i { git rev-parse --abbrev-ref HEAD  } | str trim | str collect ) $(ansi reset) ')' $(char newline) $(ansi yb) $(date format '%m/%d/%Y %I:%M:%S%.3f %p' --raw) $(ansi reset) ' ¯\\_(ツ)_/¯ ' $(char prompt) ' '] | str collect}",

```

i have this prompt
```
prompt = "za $(pwd) | = `{{$(set_title)}} {{$(git_br)}}`"
```

**Comment by ajeetdsouza** [comment] 2020-10-27 07:06
@fdncred the tests seem to be running fine for me.

[nushell_test.txt](https://github.com/ajeetdsouza/zoxide/files/5443478/nushell_test.txt)
[config.toml.txt](https://github.com/ajeetdsouza/zoxide/files/5443481/config.toml.txt)

**Comment by fdncred** [comment] 2020-10-27 12:36
I'm sorry for this and I'm not sure what to tell you but I still get errors.
[my-tests.txt](https://github.com/ajeetdsouza/zoxide/files/5445308/my-tests.txt)
here's my complete toml
[config.toml.txt](https://github.com/ajeetdsouza/zoxide/files/5445311/config.toml.txt)
i'll also try with your minified config.toml

**Comment by fdncred** [comment] 2020-10-27 12:48
unfortunately, even with the minified config.toml I still get errors.  I wonder if there's something going on with my specific version of windows or my specific version of nushell.
[my-tests-minified.txt](https://github.com/ajeetdsouza/zoxide/files/5445360/my-tests-minified.txt)

Microsoft Windows [Version 10.0.19042.572]

|version|commit_hash|features|
|-|-|-|
|0.21.1|1b0ed305162641e2e0fa937f3ca18d4527e4903b|default, clipboard, trash|

The nushell version is based on a nushell PR that I just submitted #2704

**Comment by ajeetdsouza** [comment] 2021-03-05 18:36
Closing this:

- The issue no longer occurs on my machine after adding the code for random backoff + retry
- There is no other way to resolve this issue, since atomic moves are not provided by Windows
- This only occurs when `add` is called in a loop with many threads - which is not a realistic use case for zoxide

If you want to experiment on your system, you can try tweaking the parameters [here](https://github.com/ajeetdsouza/zoxide/blob/22d19a74b2587fa14f59ef0e6cefe1f7b67f9016/src/db/mod.rs#L139) and [here](https://github.com/ajeetdsouza/zoxide/blob/22d19a74b2587fa14f59ef0e6cefe1f7b67f9016/src/db/mod.rs#L147) to see if it helps.

**Closed by ajeetdsouza** 2021-03-05 18:36 UTC
Labels: C-bug
