### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by NightMachinary** [ajeetdsouza/zoxide#98] opened 2020-07-19 10:41 UTC
I get this error on any cd:

```
Error: could not deserialize database

Caused by:
    io error: failed to fill whole buffer
Error: could not deserialize database

Caused by:
    io error: failed to fill whole buffer
```

I guess this might be because the database doesn’t do sufficient escaping? I previously had problems with zlua because I used “|” in my directory names.

**Comment by NightMachinary** [comment] 2020-07-19 10:44
I checked the database; It had become an empty file:

```
~/.z.dir
❯ ll        
.rw-rw-r-- 0 eva 17 Jul  2:30 db.zo
```

I renamed it and the error went away. So the issue seems to be that zoxide needs to have backups of its database, as the database is prone to spontaneous corruption.

**Comment by ajeetdsouza** [comment] 2020-07-21 13:42
Hey @NightMachinary,

What version of zoxide are you running? There were corruption issues before v0.3.0, but they've been fixed now.

**Comment by NightMachinary** [comment] 2020-07-21 15:02
[**@Ajeet D'Souza**](https://github.com/ajeetdsouza) commented on [Jul 21, 2020, 6:12 PM GMT+4:30](https://github.com/ajeetdsouza/zoxide/issues/98#issuecomment-661869188 "2020-07-21T13:42:29Z - Replied by Github Reply Comments"):
> Hey [@NightMachinary](https://github.com/NightMachinary),
> 
> What version of zoxide are you running? There were corruption issues before v0.3.0, but they've been fixed now.

zoxide v0.4.0-unknown

**Comment by ajeetdsouza** [comment] 2020-07-27 10:02
That is odd. zoxide creates and writes to a tempfile, and if that succeeds, it replaces the actual DB via a filesystem rename (which is an atomic operation). A successful write will always have a minimum of 4 bytes, so this should never happen.

I'm not sure backups are the best approach here, but do you think you could somehow reproduce the bug?

**Comment by ajeetdsouza** [comment] 2020-10-30 15:37
Closing this due to inactivity. If this occurs again, do create a separate issue.

**Closed by ajeetdsouza** 2020-10-30 15:37 UTC
Labels: C-bug
