### ISSUE TITLE
ls -p not supported on macOS

### ISSUE THREAD

**Issue by rickythefox** [ajeetdsouza/zoxide#373] opened 2022-03-31 22:42 UTC
`utils.rs:50` uses the `-r` flag for ls, this is not present on MacOS which leads to fzf showing an error in the preview box. Would submit a PR but my Rust is... well, rusty. Excuse the bad pun.

Worked around by defining this function in fish:
```
function ls --wraps=/usr/local/bin/exa --wraps=ls --description 'replaces ls -p'
  # Remove unsupported -p option
  if set -l index (contains -i -- -p $argv)
    set --erase argv[$index]
  end
  ls $argv
end
```

**Comment by ajeetdsouza** [comment] 2022-04-01 00:14
Duplicate of https://github.com/ajeetdsouza/zoxide/issues/328

**Closed by ajeetdsouza** 2022-04-01 00:14 UTC
