### ISSUE TITLE
cd:1: maximum nested function level reached; increase FUNCNEST?

### ISSUE THREAD

**Issue by JonasFovea** [ajeetdsouza/zoxide#700] opened 2024-02-15 16:54 UTC
Hi, I've just installed zoxide for the first time, after seeing [the video by Dreams of Autonomy](https://youtu.be/aghxkpyRVDY?si=SyKgQhPVvOf-GEKI), which was great!

I then also tried to replace the `cd` command by adding the following line in my `.zshrc` file:
```
eval "$(zoxide init --cmd cd zsh)"
``` 
Sourcing it, results in an reoccuring error when running `cd` afterwards:
```
~ cd /whatever
cd:1: maximum nested function level reached; increase FUNCNEST?
```
After displaying the error message, the current working directory hasn't changed.
Removing the `--cmd cd` option solves this problem when using the `z` command instead.

Did I do something wrong?

My system is running Ubuntu 22.04, using the zsh.

**Comment by AnshumanNeon** [comment] 2024-02-15 17:21
i think you can just keep that line as it is and add this to your .zshrc file
```
alias cd=z
```

**Comment by JonasFovea** [comment] 2024-02-15 17:27
Yes, that's true.
But if there is an argument especially for doing this, I'd rather do that.

And if there is a bug in this feature, it should be fixed...

**Comment by NzudemK** [comment] 2024-02-15 17:40
I have the same issue.If i do zoxide -V i get zoxide v0.4.3-unknown, so maybe there is a problem with the package version.

**Comment by ajeetdsouza** [comment] 2024-02-15 17:52
Duplicate of https://github.com/ajeetdsouza/zoxide/issues/694; your zoxide is out of date.

**Closed by ajeetdsouza** 2024-02-15 17:52 UTC

**Comment by JonasFovea** [comment] 2024-02-15 17:59
I installed it via apt, today.
Ist apt no longer supported?
